default_language_version:
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
    -   id: nbqa-black
        exclude: ^docs/
    -   id: nbqa-isort
        exclude: ^docs/
    -   id: nbqa-flake8
        exclude: ^docs/
    -   id: nbqa-mypy
        exclude: ^docs/

-   repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.9.1
    hooks:
    -   id: cython-lint
    -   id: double-quote-cython-strings

-   repo: https://github.com/PyCQA/isort
    rev: 5.11.1
    hooks:
    -   id: isort
        exclude: ^docs/

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        exclude: ^docs/

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: ^docs/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        exclude: ^docs/
